# Configuration file for the Strava Analysis Tool.

[paths]
strava_tokens_file = 'Credentials/Tokens.txt'
here_creds_file = 'Credentials/credentials.properties'
activity_data_file = 'Data/StravaActivityData.json'
geo_data_file = 'Data/StravaGeoData.geojson'

[data]
enable_reverse_geocoding = true

[analysis]
plot_colour_palette = "Dark2"
heatmap_colour_palette = "viridis"
heatmap_column_wrap = 5
