# Configuration file for the Strava Analysis Tool.

[paths]
tokens_file = 'Tokens.txt'
activity_data_file = 'Data/StravaActivityData.json'
geo_data_file = 'Data/StravaGeoData.geojson'

[data]
enable_reverse_geocoding = false

[analysis]
plot_colour_palette = "Dark2"
heatmap_colour_palette = "viridis"
heatmap_column_wrap = 5