name: strava-analysis-tool
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - geopy
  - matplotlib
  - numpy
  - pandas
  - polyline
  - python=3.9
  - python-dateutil
  - requests
  - seaborn
  - toml
  - xyzspaces
